version: '2.2'
services:
  django:
    volumes:
      - '.:/usr/src/sc'
    environment:
      DEBUG: 'False'
      GEONODE_LB_HOST_IP: sc.puerti.co
      GEONODE_LB_PORT: 80
      SITEURL: https://sc.puerti.co/
      ALLOWED_HOSTS: "['sc.puerti.co', 'localhost']"
      GEOSERVER_PUBLIC_LOCATION: https://sc.puerti.co/gs/
      GEOSERVER_WEB_UI_LOCATION: https://sc.puerti.co/geoserver/

  celery:
    environment:
      DEBUG: 'False'
      GEONODE_LB_HOST_IP: sc.puerti.co
      GEONODE_LB_PORT: 80
      SITEURL: https://sc.puerti.co/
      ALLOWED_HOSTS: "['sc.puerti.co', ]"
      GEOSERVER_PUBLIC_LOCATION: https://sc.puerti.co/gs/
      GEOSERVER_WEB_UI_LOCATION: https://sc.puerti.co/geoserver/

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: sc.puerti.co
      GEONODE_LB_PORT: 80
      NGINX_BASE_URL: https://sc.puerti.co/
